package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.Set;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.ParallelRaceGroup;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.RobotContainer;
import frc.robot.commands.AutoPilot.AutoPilotV2Command;
import frc.robot.commands.PidToPose.PidToPoseCommand;
import frc.robot.constants.FeatureSwitches;
import frc.robot.constants.FieldConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.lib.AllianceSymmetry;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private boolean m_allowVisionOdometryUpdates = true;
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    private ChassisSpeeds m_lastSpeeds = new ChassisSpeeds();
    private double m_lastSpeedsTime = 0.0;
    private final LinearFilter m_axFilter = LinearFilter.movingAverage(5); // 5-tap moving average
    private final LinearFilter m_ayFilter = LinearFilter.movingAverage(5);

    /* Swerve features for aim calculations and visualization */
    private final SwerveFeatures m_swerveFeatures;

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        m_swerveFeatures = new SwerveFeatures(this);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        m_swerveFeatures = new SwerveFeatures(this);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        m_swerveFeatures = new SwerveFeatures(this);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        // Update swerve features (handles aim visualization auto-clearing)
        m_swerveFeatures.periodic();
        checkForSetPose();
    }

    /**
     * Gets the SwerveFeatures instance for aim-related calculations.
     * 
     * @return The SwerveFeatures instance
     */
    public SwerveFeatures getFeatures() {
        return m_swerveFeatures;
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        if (!m_allowVisionOdometryUpdates) {
            return;
        }
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        if (!m_allowVisionOdometryUpdates) {
            return;
        }
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    public void setVisionOdometryUpdatesEnabled(boolean enabled) {
        m_allowVisionOdometryUpdates = enabled;
    }

    public boolean areVisionOdometryUpdatesEnabled() {
        return m_allowVisionOdometryUpdates;
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Gets the filtered linear acceleration magnitude of the robot.
     * 
     * @return Linear acceleration in m/s²
     */
    public double getFilteredAcceleration() {
        ChassisSpeeds currentSpeeds = getState().Speeds;
        double currentTime = edu.wpi.first.wpilibj.Timer.getFPGATimestamp();
        double dt = currentTime - m_lastSpeedsTime;

        if (dt == 0.0 || m_lastSpeedsTime == 0.0) {
            // First call or no time elapsed
            m_lastSpeeds = currentSpeeds;
            m_lastSpeedsTime = currentTime;
            return 0.0; // Return zero acceleration
        }

        // Calculate raw acceleration
        double ax = (currentSpeeds.vxMetersPerSecond - m_lastSpeeds.vxMetersPerSecond) / dt;
        double ay = (currentSpeeds.vyMetersPerSecond - m_lastSpeeds.vyMetersPerSecond) / dt;

        // Apply filtering
        ax = m_axFilter.calculate(ax);
        ay = m_ayFilter.calculate(ay);

        // Update for next call
        m_lastSpeeds = currentSpeeds;
        m_lastSpeedsTime = currentTime;

        // Return magnitude of linear acceleration
        return Math.hypot(ax, ay);
    }

    /**
     * Calculates the angle from the robot to a target pose.
     * Returns the angle in field coordinates, adjusted for operator perspective.
     * 
     * @param targetPose The target pose (should be already flipped for alliance if
     *                   needed)
     * @return The angle the robot should face, relative to operator perspective
     */
    public Rotation2d getAngleToTarget(Pose2d targetPose) {
        return m_swerveFeatures.getAngleToTarget(targetPose);
    }

    /**
     * Calculates the angle from the robot to a target pose, accounting for the
     * robot's velocity.
     * Uses a lookup table of distances and flight times for more accurate
     * interpolation.
     * This is the most accurate method for accounting for varying launch angles at
     * different distances.
     * 
     * The lookup table should contain actual measured flight times at various
     * distances.
     * The method will interpolate between the nearest data points.
     * 
     * @param targetPose The target pose (should be already flipped for
     *                   alliance if needed)
     * @return The angle the robot should face to hit the target, accounting for
     *         robot velocity
     */
    public Rotation2d getAngleToTargetWithVelocityCompensation(Pose2d targetPose) {
        return m_swerveFeatures.getAngleToTargetWithVelocityCompensation(targetPose);
    }

    public void publishDriveOutputVoltage() {
        SwerveModule<TalonFX, TalonFX, CANcoder>[] modules = this.getModules();

        for (int j = 0; j < modules.length; j++) {
            SmartDashboard.putNumber(SWERVE_DRIVE + "DriveMotor_OutputVoltage_" + j,
                    modules[j].getDriveMotor().getMotorVoltage().getValueAsDouble());
        }
    }

    public void publishMotorCurrent() {
        SwerveModule<TalonFX, TalonFX, CANcoder>[] modules = this.getModules();

        double supplyCurrentSum = 0;

        for (int j = 0; j < modules.length; j++) {
            if (FeatureSwitches.PUBLISH_INDIVIDUAL_DRIVE_CURRENTS) {
                SmartDashboard.putNumber(SWERVE_DRIVE + "DriveMotor_StatorCurrent_" + j,
                        modules[j].getDriveMotor().getStatorCurrent().getValueAsDouble());
                SmartDashboard.putNumber(SWERVE_DRIVE + "DriveMotor_SupplyCurrent_" + j,
                        modules[j].getDriveMotor().getSupplyCurrent().getValueAsDouble());
                SmartDashboard.putNumber(SWERVE_DRIVE + "DriveMotor_TorqueCurrent_" + j,
                        modules[j].getDriveMotor().getTorqueCurrent().getValueAsDouble());
            }

            supplyCurrentSum += modules[j].getDriveMotor().getSupplyCurrent().getValueAsDouble();

        }

        SmartDashboard.putNumber(SWERVE_DRIVE + "DriveMotor_Cumulative_SupplyCurrents", supplyCurrentSum);
    }

    public void publishDrivePidErrors() {
        SwerveModule<TalonFX, TalonFX, CANcoder>[] modules = this.getModules();

        for (int j = 0; j < modules.length; j++) {
            TalonFX driveMotor = modules[j].getDriveMotor();

            SmartDashboard.putNumber(
                    SWERVE_DRIVE + "DriveMotor_ClosedLoopError_" + j,
                    driveMotor.getClosedLoopError().getValueAsDouble());

            SmartDashboard.putNumber(
                    SWERVE_DRIVE + "DriveMotor_ClosedLoopReference_" + j,
                    driveMotor.getClosedLoopReference().getValueAsDouble());

            SmartDashboard.putNumber(
                    SWERVE_DRIVE + "DriveMotor_ClosedLoopOutput_" + j,
                    driveMotor.getClosedLoopOutput().getValueAsDouble());

        }
    }

    public Command driveToPose(Supplier<Optional<Pose2d>> targetPoseSupplier, boolean flipPoseForRedAlliance) {
        Supplier<Pose2d> poseSupplier = () -> (targetPoseSupplier.get().get());

        // return Commands.sequence(
        // Commands.runOnce(() -> {
        // System.out.println("DriveToPose Called with targetPose: " +
        // targetPoseSupplier.get());
        // }),
        // new PidToPoseCommand.Builder(poseSupplier, this,
        // "DriveToPose").withTolerance(2)
        // .withFlipPoseForAlliance(flipPoseForRedAlliance).build());
        return new PidToPoseCommand.Builder(poseSupplier, this, "DriveToPose").withTolerance(2)
                .withFlipPoseForAlliance(flipPoseForRedAlliance).withTolerance(0.5).build();
    }

    public Command driveToPoseAP(Supplier<Optional<Pose2d>> targetPoseSupplier, boolean flipPoseForRedAlliance) {
        Supplier<Pose2d> poseSupplier = () -> (targetPoseSupplier.get().get());// TODO pass the real supplier in so it
                                                                               // can constantly update its position,
                                                                               // based on user input
        return new AutoPilotV2Command.Builder(poseSupplier, this, "DriveToPose")
                .withFlipPoseForAlliance(flipPoseForRedAlliance)
                .withProfileThresholds(
                        AutoPilotV2Command.DEFAULT_XY_THRESHOLD, 2.0, AutoPilotV2Command.DEFAULT_BEELINE_THRESHOLD)
                .withVelocityThreshold(0.1)// was 5
                .build();
    }

    public void publishDistanceToHub() {
        SmartDashboard.putNumber(SWERVE_DRIVE + "DistanceToHub",
                m_swerveFeatures.getDistanceToHub(this, FieldConstants.ALLIANCE_HUB_POSITION));
    }

    private static final SendableChooser<Pose2d> positionChooser = new SendableChooser<>();

    private static final String SWERVE_DRIVE = "SwerveDrive/";
    private static final String SET_OVERRIDE_POSE = "Set Override Pose";
    private static final String OVERRIDE_POSE = "Override Pose";

    public void initOverridePose() {
        SmartDashboard.putNumber(SWERVE_DRIVE + "OverridePose_X", 0);
        SmartDashboard.putNumber(SWERVE_DRIVE + "OverridePose_Y", 0);
        SmartDashboard.putBoolean(SWERVE_DRIVE + SET_OVERRIDE_POSE, false);

        positionChooser.addOption("NONE", null);
        positionChooser.addOption("RightStart", FieldConstants.RIGHT_START);
        positionChooser.addOption("CenterStart", FieldConstants.CENTER_START);
        positionChooser.addOption("LeftStart", FieldConstants.LEFT_START);
        SmartDashboard.putData(SWERVE_DRIVE + OVERRIDE_POSE, positionChooser);
    }

    public void checkForSetPose() {
        boolean value = SmartDashboard.getBoolean(SWERVE_DRIVE + SET_OVERRIDE_POSE, false);
        if (value) {
            // override pose button pushed
            Pose2d overridePose = positionChooser.getSelected();

            if (overridePose == null) {
                double x = SmartDashboard.getNumber(SWERVE_DRIVE + "OverridePose_X", 0);
                double y = SmartDashboard.getNumber(SWERVE_DRIVE + "OverridePose_Y", 0);
                resetPose(new Pose2d(x, y, Rotation2d.kZero));
            } else {
                // override pose selected
                if (AllianceSymmetry.isBlue()) {
                    resetPose(overridePose);
                } else {
                    resetPose(AllianceSymmetry.flip(overridePose));
                }
            }

            // disable set override pose button, resets the UI
            SmartDashboard.putBoolean(SWERVE_DRIVE + SET_OVERRIDE_POSE, false);
        }
    }
}
