"""classify.py, content.py and dedupe.py: synthetic logs with known answers, then the real sample logs."""
import pathlib
import struct
import sys

import pytest

import wpilog_builder as wb
from janitor.core import classify as cl
from janitor.core import content, dedupe
from wpilog_utils.index import build_index, load_index
from wpilog_utils.trim import Segment, TrimPlan, resolve_plan

NOTES = pathlib.Path(__file__).resolve().parents[3] / 'notes' / '6-20'
BOTH = ('replay', 'logbench')
N = 200                      # cycles in the synthetic logs


def d(v):
    return wb.double(v)


def make_log(series, cycle_us=20_000, t0=1_000_000, offsets=None, typ='double'):
    """series: {name: [values per cycle]}; a value of None means "not logged this cycle". `offsets` shifts an
    entry's timestamps (in µs) so equal data is logged at different instants. Cycles are marked by /Timestamp."""
    b = wb.LogBuilder()
    b.entry('/Timestamp', 'int64', t0)
    for name in series:
        b.entry(name, typ if not isinstance(typ, dict) else typ.get(name, 'double'), t0)
    n = max(len(v) for v in series.values())
    rows = []
    for k in range(n):
        t = t0 + k * cycle_us
        b.data('/Timestamp', t, wb.int64(t))
        for name, vals in series.items():
            if k < len(vals) and vals[k] is not None:
                b.data(name, t + (offsets or {}).get(name, 0), d(vals[k]) if isinstance(vals[k], (int, float)) else vals[k])
    return b.build()


def wave(k, f=0.37):
    return round(((k * f) % 7) - 3, 3)


def stats_of(raw, ranges=None):
    ix = build_index(raw)
    return ix, content.analyze_content(raw, ix.header_end, ranges)


def by_name(stats):
    return {s.name: s for s in stats.values()}


# ── classify ────────────────────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize('name,typ,expected', [
    ('/RealOutputs/Vision/Left/AcceptedPoses', 'struct:Pose2d[]', cl.OUTPUT),
    ('/ReplayOutputs/Foo', 'double', cl.OUTPUT),
    ('/Vision/Left/RawEstimatedPoses', 'struct:Pose3d[]', cl.REPLAY_INPUT),
    ('/DriverStation/Enabled', 'boolean', cl.REPLAY_INPUT),
    ('/SystemStats/CPUTempCelsius', 'double', cl.REPLAY_INPUT),
    ('/Timestamp', 'int64', cl.STRUCTURAL),
    ('/.schema/struct:Pose2d', 'structschema', cl.STRUCTURAL),
    ('/Anything/at/all', 'structschema', cl.STRUCTURAL),
    ('/Janitor/SegmentMap', 'string', cl.JANITOR),
    ('Pickup/VelocityRPS', 'double', cl.REPLAY_INPUT),          # no leading slash
])
def test_classify(name, typ, expected):
    assert cl.classify(name, typ) == expected


def test_protection_profiles():
    inp, out, vis_out = '/Pickup/VelocityRPS', '/RealOutputs/Pickup/VelocityRPS', '/RealOutputs/Vision/Left/AcceptedPoses'
    assert cl.protection(inp, 'double', ('replay',)) and not cl.protection(inp, 'double', ())
    assert not cl.protection(out, 'double', ('replay',))                       # outputs are regenerated by replay...
    assert cl.protection(vis_out, 'x', ('logbench',)) and not cl.protection(vis_out, 'x', ('replay',))   # ...but logbench reads them
    assert cl.protection('/Timestamp', 'int64', ()) and cl.protection('/.schema/struct:Pose2d', 'structschema', ())   # always
    assert cl.protection('/Janitor/SegmentMap', 'string', ())
    assert 'replay' in cl.protection(inp, 'double', ('replay',))
    assert not cl.protection('/VisionX/thing', 'x', ('logbench',))             # prefix match respects '/' boundaries


@pytest.mark.skipif(not NOTES.exists(), reason='sample logs not present')
def test_logbench_profile_covers_what_logbench_actually_reads():
    """Runs the real lookups of vision-analyzer/logbench on a sample log and checks every signal they pick is protected."""
    tools = pathlib.Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(tools / 'vision-analyzer'))
    from vision_analyzer import metrics as m
    from vision_analyzer.parser import parse_wpilog
    signals = parse_wpilog(str(next(NOTES.glob('*baseline.wpilog'))))
    picked = [k for k in m.find_drivetrain_speeds(signals) if k]
    cams = m.discover_cameras(signals)
    picked += [f'RealOutputs/Vision/{c}/AcceptedPoses' for c in cams] + [f'Vision/{c}/RawEstimatedPoses' for c in cams]
    picked += ['DriverStation/Enabled', 'DriverStation/Autonomous']
    assert cams and picked
    for k in picked:
        assert cl.protection('/' + k, 'x', ('logbench',)), f'{k} is read by logbench/vision-analyzer but not protected'


# ── content: per-entry statistics ───────────────────────────────────────────────────────────────

def test_basic_statistics_and_change_counting():
    raw = make_log({'/Sensor/A': [wave(k) for k in range(N)], '/Cfg/K': [7.0] + [7.0] * (N - 1)})
    ix, st = stats_of(raw)
    a, k = by_name(st)['/Sensor/A'], by_name(st)['/Cfg/K']
    assert a.n_records == N and a.bytes > 0 and not a.constant and a.n_changes > 20
    assert a.num_min == pytest.approx(-3) and a.num_max < 4 and a.num_mean == pytest.approx(sum(wave(i) for i in range(N)) / N)
    assert k.constant and k.distinct == 1 and k.n_changes == 0 and k.num_min == k.num_max == 7.0
    assert st[ix.cycle_entry_id].n_records == N
    assert sum(s.bytes for s in st.values()) == ix.data_bytes                    # the window is the whole log


def test_distinct_count_stops_at_the_cap_and_samples_are_kept():
    raw = make_log({'/X': [float(k) for k in range(300)]})
    _, st = stats_of(raw)
    x = by_name(st)['/X']
    assert x.distinct == content.DISTINCT_CAP and x.distinct_capped and not x.constant
    assert [struct.unpack('<d', s)[0] for s in x.samples] == [0.0, 1.0, 2.0]


def test_hashes_depend_on_values_and_times_separately():
    vals = [wave(k) for k in range(N)]
    raw = make_log({'/A': vals, '/B': vals, '/C': vals, '/D': vals[::-1]}, offsets={'/C': 5_000})
    _, st = stats_of(raw)
    n = by_name(st)
    assert n['/A'].seq_hash == n['/B'].seq_hash == n['/C'].seq_hash != n['/D'].seq_hash
    assert n['/A'].time_hash == n['/B'].time_hash != n['/C'].time_hash


def test_a_window_restricts_everything_to_the_kept_periods():
    # /S is constant for the first 100 cycles, then changes every cycle
    raw = make_log({'/S': [1.0] * 100 + [float(k) for k in range(100)]})
    ix = build_index(raw)
    first, second = TrimPlan([Segment(0.0, 1.9)]), TrimPlan([Segment(2.0, 4.0)])
    r1 = resolve_plan(ix, first).ranges
    r2 = resolve_plan(ix, second).ranges
    s1 = by_name(content.analyze_content(raw, ix.header_end, [(r.lo_us, r.hi_us) for r in r1]))['/S']
    s2 = by_name(content.analyze_content(raw, ix.header_end, [(r.lo_us, r.hi_us) for r in r2]))['/S']
    whole = by_name(content.analyze_content(raw, ix.header_end))['/S']
    assert s1.constant and s1.n_records == 95 and not whole.constant and not s2.constant
    assert s1.n_records + s2.n_records <= whole.n_records
    assert s2.first_ts_us >= r2[0].lo_us


def test_entries_with_no_records_in_the_window_are_still_listed():
    raw = make_log({'/Early': [1.0, 2.0, 3.0] + [None] * (N - 3), '/Always': [wave(k) for k in range(N)]})
    ix = build_index(raw)
    rng = [(r.lo_us, r.hi_us) for r in resolve_plan(ix, TrimPlan([Segment(2.0, 3.0)])).ranges]
    st = by_name(content.analyze_content(raw, ix.header_end, rng))
    assert st['/Early'].n_records == 0 and not st['/Early'].constant and st['/Always'].n_records > 0


def test_preview_values_are_short_and_readable():
    assert content.preview_value(wb.double(3.5), 'double') == '3.5'
    assert content.preview_value(wb.boolean(True), 'boolean') == 'True'
    assert content.preview_value(b'hello', 'string') == "'hello'"
    long = struct.pack('<10d', *range(10))
    assert content.preview_value(long, 'double[]').endswith('10 items]')
    assert len(content.preview_value(b'x' * 500, 'string', limit=40)) == 40
    assert content.preview_value(b'\x01\x02', 'mystery') == '2 bytes'


# ── dedupe ──────────────────────────────────────────────────────────────────────────────────────

def test_constants_are_never_grouped_as_duplicates():
    raw = make_log({'/Zero/A': [0.0] * N, '/Zero/B': [0.0] * N, '/Zero/C': [0.0] * N, '/Real': [wave(k) for k in range(N)]})
    _, st = stats_of(raw)
    names = {st[i].name for i in dedupe.constants(st)}
    assert {'/Zero/A', '/Zero/B', '/Zero/C'} <= names and '/Real' not in names
    assert dedupe.exact_groups(st, BOTH) == []


def test_identical_and_values_only_groups_with_keeper_and_recoverable_bytes():
    v = [wave(k) for k in range(N)]
    raw = make_log({'/Pickup/Velocity': v, '/RealOutputs/Pickup/Velocity': v, '/Vision/Raw': v[:100] + v[:100],
                    '/Vision/Copy': v[:100] + v[:100], '/Other/Different': [wave(k, 0.11) for k in range(N)]},
                   offsets={'/RealOutputs/Pickup/Velocity': 3_000})
    _, st = stats_of(raw)
    groups = {g.kind: g for g in dedupe.exact_groups(st, BOTH)}
    assert set(groups) == {'identical', 'values'}
    g = groups['values']
    assert st[g.keeper].name == '/Pickup/Velocity'                                   # the replay-input side is kept
    assert [st[i].name for i in g.members if i != g.keeper] == ['/RealOutputs/Pickup/Velocity']
    assert g.recoverable_bytes == st[[i for i in g.members if i != g.keeper][0]].bytes
    assert g.blocked == [] and not g.weak and 'different instants' in g.evidence
    ident = groups['identical']
    assert ident.evidence.startswith('all 200 values match') and 'same instants' in ident.evidence


def test_protected_non_keepers_are_reported_as_blocked():
    v = [wave(k) for k in range(N)]
    raw = make_log({'/Vision/A/Raw': v, '/Vision/A/Copy': v})
    _, st = stats_of(raw)
    (g,) = dedupe.exact_groups(st, BOTH)
    assert len(g.blocked) == 1 and g.blocked[0] != g.keeper                          # both are replay inputs
    (g2,) = dedupe.exact_groups(st, ())
    assert g2.blocked == []                                                          # nothing protected -> nothing blocked


def test_short_series_that_match_are_flagged_weak():
    raw = make_log({'/A/Flag': [0.0] * 50 + [1.0] * 150, '/B/Flag': [0.0] * 50 + [1.0] * 150})
    _, st = stats_of(raw)
    (g,) = dedupe.exact_groups(st, BOTH)
    assert g.weak                                                                    # one flip each: could easily be coincidence


def test_near_duplicates_and_same_name_different_data():
    v = [wave(k) for k in range(N)]
    almost = list(v); almost[100] += 0.5                                              # 1 of 200 differs -> 99.5%, below 99.9%
    raw = make_log({'/Foo/Bar': v, '/RealOutputs/Foo/Bar': almost})
    ix, st = stats_of(raw)
    ex = dedupe.exact_groups(st, BOTH)
    near, twins = dedupe.near_groups_and_twins(raw, ix.header_end, st, ex, BOTH)
    assert ex == [] and near == []                                                   # 99.5% is under the threshold
    (t,) = twins
    assert t.relation == 'different' and '99.5' in t.note and t.key == 'Foo/Bar'

    big = [wave(k) for k in range(3000)]
    nearly = list(big); nearly[1500] += 0.5                                           # 1 of 3000 differs -> 99.97%
    raw = make_log({'/Foo/Bar': big, '/Baz/Qux': nearly})
    ix, st = stats_of(raw)
    near, twins = dedupe.near_groups_and_twins(raw, ix.header_end, st, [], BOTH)
    assert len(near) == 1 and near[0].kind == 'near' and '99.97%' in near[0].evidence and twins == []


def test_twins_with_different_lengths_and_types():
    raw = make_log({'/A/x': [wave(k) for k in range(N)], '/RealOutputs/A/x': [wave(k) for k in range(50)]})
    ix, st = stats_of(raw)
    _, twins = dedupe.near_groups_and_twins(raw, ix.header_end, st, dedupe.exact_groups(st, BOTH), BOTH)
    assert twins[0].relation == 'different-length' and '200' in twins[0].note and '50' in twins[0].note


def test_name_key_strips_output_prefixes_only():
    assert dedupe.name_key('/RealOutputs/Pickup/VelocityRPS') == 'Pickup/VelocityRPS'
    assert dedupe.name_key('/Pickup/VelocityRPS') == 'Pickup/VelocityRPS'
    assert dedupe.name_key('/NT:/Shuffleboard/x') == 'Shuffleboard/x'
    assert dedupe.name_key('/RealOutputsX/a') == 'RealOutputsX/a'


def test_the_keeper_can_be_any_member_and_recoverable_excludes_it():
    v = [wave(k) for k in range(N)]
    raw = make_log({'/A/One': v, '/RealOutputs/A/One': v, '/RealOutputs/Deep/Er/Copy': v})
    _, st = stats_of(raw)
    (g,) = dedupe.exact_groups(st, ())
    assert st[g.keeper].name == '/A/One'
    assert g.recoverable_bytes == sum(st[i].bytes for i in g.members) - st[g.keeper].bytes


# ── real logs ───────────────────────────────────────────────────────────────────────────────────

@pytest.mark.skipif(not NOTES.exists(), reason='sample logs not present')
def test_real_log_findings():
    raw, ix = load_index(next(NOTES.glob('*decimateBack.wpilog')))
    st = content.analyze_content(raw, ix.header_end)
    assert sum(s.bytes for s in st.values()) == ix.data_bytes
    assert len(dedupe.constants(st)) == 206                                           # the count the plan's exploration found
    groups = dedupe.exact_groups(st, BOTH)
    strong = [g for g in groups if not g.weak]
    names = {st[i].name for g in strong for i in g.members}
    assert {'/Vision/Right/VisibleTagIds', '/Vision/Right/RawTagIdsFlat', '/Pickup/VelocityRPS', '/RealOutputs/Pickup/VelocityRPS'} <= names
    vis = next(g for g in strong if '/Vision/Right/VisibleTagIds' in {st[i].name for i in g.members})
    assert vis.kind == 'identical' and len(vis.blocked) == 1 and vis.recoverable_bytes > 100_000       # replay input: blocked
    pick = next(g for g in strong if '/Pickup/VelocityRPS' in {st[i].name for i in g.members})
    assert st[pick.keeper].name == '/Pickup/VelocityRPS' and pick.blocked == []                       # the output copy is free to drop
    assert any(g.weak for g in groups)                                                # the coincidental boolean matches exist and are marked
    near, twins = dedupe.near_groups_and_twins(raw, ix.header_end, st, groups, BOTH)
    assert near == [] and all(t.relation == 'identical' for t in twins)


@pytest.mark.skipif(not NOTES.exists(), reason='sample logs not present')
def test_real_log_window_matches_the_trimmed_size():
    raw, ix = load_index(next(NOTES.glob('*decimateBack.wpilog')))
    res = resolve_plan(ix, TrimPlan([Segment(36.8, 52.7)]))
    st = content.analyze_content(raw, ix.header_end, [(r.lo_us, r.hi_us) for r in res.ranges])
    assert sum(s.bytes for s in st.values()) == sum(sum(ix.cycle_bytes[r.first:r.last + 1]) for r in res.ranges)


def test_stopping_early_after_the_last_period_changes_nothing(monkeypatch):
    """With the index's entry list the pass ends when the last period does; the result must equal a full read,
    including entries that are only started after the window."""
    b = wb.LogBuilder()
    b.entry('/Timestamp', 'int64', 1_000_000)
    b.entry('/Early', 'double', 1_000_000)
    for k in range(300):
        t = 1_000_000 + k * 20_000
        b.data('/Timestamp', t, wb.int64(t))
        b.data('/Early', t, d(wave(k)))
        if k == 250:
            b.entry('/Late', 'double', t)                     # started long after the window
        if k >= 250:
            b.data('/Late', t, d(float(k)))
    raw = b.build()
    ix = build_index(raw)
    rng = [(r.lo_us, r.hi_us) for r in resolve_plan(ix, TrimPlan([Segment(1.0, 2.0)])).ranges]

    consumed = []
    real = content.iter_records

    def counting(buf, pos):
        for rec in real(buf, pos):
            consumed.append(1)
            yield rec

    monkeypatch.setattr(content, 'iter_records', counting)
    full = content.analyze_content(raw, ix.header_end, rng)
    n_full = len(consumed)
    consumed.clear()
    fast = content.analyze_content(raw, ix.header_end, rng, ix.entries)
    n_fast = len(consumed)

    strip = lambda st: {i: (s.name, s.type, s.n_records, s.bytes, s.n_changes, s.distinct, s.seq_hash, s.time_hash, s.first_ts_us, s.last_ts_us) for i, s in st.items()}
    assert strip(fast) == strip(full)
    assert by_name(fast)['/Late'].n_records == 0 and by_name(fast)['/Early'].n_records == 50
    assert n_full == 300 + 300 + 50 + 3                          # the full read visits every record
    assert n_fast < n_full / 2                                   # the early stop does not
